### ISSUE TITLE
MSBUILD : error MSB1006: Property is not valid.

### ISSUE THREAD

**Issue by chungsavi** [banditoth/maui-archiver-vscode#10] opened 2024-02-19 11:30 UTC
dotnet publish "*.csproj" -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64  -p:CodesignKey="iPhone Distribution: NAME., Ltd. (525P9MKHKJ)" -p:CodesignProvision="Name"
MSBuild version 17.9.4+90725d08d for .NET
MSBUILD : error MSB1006: Property is not valid.
Switch:  Ltd. (525P9MKHKJ)

There is "," character in CodesignKey. That cause of Error.

**Comment by banditoth** [comment] 2024-02-19 11:36
Hey, @chungsavi 

Could you please run this in your terminal, and pass back the result?
`security find-identity -p codesigning -v`

**Comment by banditoth** [comment] 2024-07-04 06:25
I can't reproduce this issue. With no further details, i'm closing this issue. Please reopen it, if you experience the same issue.

**Closed by banditoth** 2024-07-04 06:25 UTC

**Comment by DanielCauser** [comment] 2024-09-23 18:55
Hello, I came across the same issue. My company name is as follows:

"Apple Distribution: COMPANY NAME, Inc. (0000000000)"

A the other folk mentioned, there is a "," right in the middle of the name, which is apparently causing the issue.

**Comment by DanielCauser** [comment] 2024-09-23 19:01
Copying the command and replacing the string  `p:CodesignKey="iPhone Distribution: NAME., Ltd. (525P9MKHKJ)" ` as mentioned on the github issue bellow, fixed the problem.

https://github.com/microsoft/vscode-dotnettools/issues/934#issuecomment-2290949836
